### ISSUE TITLE
说下将来对devtools的支持方案

### ISSUE THREAD

**Issue by ksky521** [ecomfe/js-native#12]
最近在研究远程调试工具，暂命名是remote-devtools，为了方便端能力的调试，想把端能力调用也用类似san devtools的hook来实现，大概想法是：
1. 添加描述表时，将处理之后的描述表上报给devtools
2. 调用时，将args上报给devtools，有回调的，将回调函数改写，这样回调结果也能拿到上报给devtools，同时记录执行实现

页面效果可以参考下图：

![image](https://user-images.githubusercontent.com/1073262/117515130-ef1dea80-afc7-11eb-9462-b2de5d31a101.png)

目标：
1. 可以快速获取框架支持的所有端能力描述表，支持导出功能
2. 端能力调用记录（参数、回调、执行时间等）
3. 配合websocket + chrome devTools protocol，实现一些自动化测试脚本编写？！

**Comment by ksky521** [comment]
1. 添加上报：https://github.com/ecomfe/js-native/blob/master/index.js#L567  ，在这里return之前可以上报一份
2. 调用发现了在`invokeDescription`和`buildAPIMethod`两个地方，可以`invokeDescription`中调用`buildAPIMethod`，统一收口到buildAPIMethod的返回函数，然后进行拦截

**Comment by errorrik** [comment]
### 命名

命名的话，remote感觉太泛了，就叫js-native-devtools呗，或者别的更准确的也行

### 关于开发时的模拟和测试

- 描述表的话，能不能支持导入来实现模拟（import from file / import from URL）？
- 能否管理导入的描述表，使用其中的一个来模拟
- 对当前使用的描述表，能否选择能力，部分生效或部分不生效，来模拟不同版本app上的能力差

### 关于调用记录

这个应用场景是真机调试吗？

### 关于自动化测试脚本编写

这个我建议在管理平台做。

**Comment by ksky521** [comment]
remote devtools是一个chrome devtools的远程调试版本，类似Weinre，而js native这个只是其中一个插件，自动化测试也是remote devtools的一个feature，不是js native插件的专属，原理是通过脚本建立web socket链接发送chrome devtool protocol到页面执行指令，可以发一些指令到页面自动执行一些jsnative调用，然后获取回调看符合预期不

**Comment by ksky521** [comment]
remote devtools已经发布小版本了，https://www.npmjs.com/package/devtools-pro
对应的js-native-monitor的也在开发中了

**Comment by ksky521** [comment]
这个issue先关了，最后决定从boxx上动手术吧，原因是boxx里面new了一个apiContainer，所以js-native中是拿不到所有的描述表
![image](https://user-images.githubusercontent.com/1073262/118097693-9904d900-b405-11eb-8e70-e0af419330b8.png)
